### ISSUE TITLE
Impressive collection

### ISSUE THREAD

**Issue by yongduek** [Jyouhou/SceneTextPapers#1]
Thanks for such a wonderful job.

Just thought if 'multi-lingual detection/recogtion' might be an item in this globalized world.

**Comment by longshangbang** [comment]
Thanks for your appreciation! 

Indeed, multi-lingual is another important topic. So far, we haven't seen any papers with main focus on it that have been published in major conferences/journals (by the time the paper was submitted). 

As addressed in our survey paper, it is worthwhile to study whether it is an outstanding challenge, or existing methods can already perform well enough.

**Comment by MingzhouZhang** [comment]
Thanks a lot for the wonderful job.

**Comment by sdzbft** [comment]
I am more thankful than I can express, thanks for your collection and sharing. 
wonderful job!!!
